// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'readingorder.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ReadingOrder _$ReadingOrderFromJson(Map<String, dynamic> json) => ReadingOrder(
      readingorderCode: json['readingordeR_CODE'] as String,
      workorderbatchCode: json['workorderbatcH_CODE'] as String?,
      readingordertypeCode: json['readingordertypE_CODE'] as String?,
      itineraryCode: json['itinerarY_CODE'] as String?,
      sequence: ReadingOrder._toDouble(json['sequence']),
      creationdate: json['creationdate'] as String?,
      startdate: json['startdate'] as String?,
      enddate: json['enddate'] as String?,
      previousindex: ReadingOrder._toDouble(json['previousindex']),
      previousindexdate: json['previousindexdate'] as String?,
      previousindexreasonCode: json['previousindexreasoN_CODE'] as String?,
      envisagedindex: ReadingOrder._toDouble(json['envisagedindex']),
      maximumindex: ReadingOrder._toDouble(json['maximumindex']),
      minimumindex: ReadingOrder._toDouble(json['minimumindex']),
      newIndex: ReadingOrder._toDouble(json['newindex']),
      newindexdate: json['newindexdate'] as String?,
      executedbypersonCode: json['executedbypersoN_CODE'] as String?,
      roundCode: json['rounD_CODE'] as String?,
      streetname1: json['streetnamE1'] as String?,
      streetname2: json['streetnamE2'] as String?,
      postalcode: json['postalcode'] as String?,
      city: json['city'] as String?,
      internalCounter: ReadingOrder._toBool(json['internaL_COUNTER']),
      name: json['name'] as String?,
      name2: json['namE2'] as String?,
      contractCode: json['contracT_CODE'] as String?,
      installationCode: json['installatioN_CODE'] as String?,
      pricelistCode: json['pricelisT_CODE'] as String?,
      assetCode: json['asseT_CODE'] as String?,
      productCode: json['producT_CODE'] as String?,
      serialnumber: json['serialnumber'] as String?,
      information: json['information'] as String?,
      externalreference: json['externalreference'] as String?,
      readingorderresultCode: json['readingorderresulT_CODE'] as String?,
      readingorderresultnoteCode:
          json['readingorderresultnotE_CODE'] as String?,
      digitsnumber: (json['digitsnumber'] as num?)?.toInt(),
      coefficient: ReadingOrder._parseDecimal(json['coefficient']),
      zwnummer: json['zwnummer'] as String?,
      zpruefkl: json['zpruefkl'] as String?,
      zzwtyp: json['zzwtyp'] as String?,
      zkennziff: json['zkennziff'] as String?,
      zwert1: json['zwerT1'] as String?,
      itinerarycodenavigation: json['itinerarY_CODENavigation'] as String?,
      workorderbatchcodenavigation:
          json['workorderbatcH_CODENavigation'] as String?,
    );

Map<String, dynamic> _$ReadingOrderToJson(ReadingOrder instance) =>
    <String, dynamic>{
      'readingordeR_CODE': instance.readingorderCode,
      'workorderbatcH_CODE': instance.workorderbatchCode,
      'readingordertypE_CODE': instance.readingordertypeCode,
      'itinerarY_CODE': instance.itineraryCode,
      'sequence': instance.sequence,
      'creationdate': instance.creationdate,
      'startdate': instance.startdate,
      'enddate': instance.enddate,
      'previousindex': instance.previousindex,
      'previousindexdate': instance.previousindexdate,
      'previousindexreasoN_CODE': instance.previousindexreasonCode,
      'envisagedindex': instance.envisagedindex,
      'maximumindex': instance.maximumindex,
      'minimumindex': instance.minimumindex,
      'newindex': instance.newIndex,
      'newindexdate': instance.newindexdate,
      'executedbypersoN_CODE': instance.executedbypersonCode,
      'rounD_CODE': instance.roundCode,
      'streetnamE1': instance.streetname1,
      'streetnamE2': instance.streetname2,
      'postalcode': instance.postalcode,
      'city': instance.city,
      'internaL_COUNTER': instance.internalCounter,
      'name': instance.name,
      'namE2': instance.name2,
      'contracT_CODE': instance.contractCode,
      'installatioN_CODE': instance.installationCode,
      'pricelisT_CODE': instance.pricelistCode,
      'asseT_CODE': instance.assetCode,
      'producT_CODE': instance.productCode,
      'serialnumber': instance.serialnumber,
      'information': instance.information,
      'externalreference': instance.externalreference,
      'readingorderresulT_CODE': instance.readingorderresultCode,
      'readingorderresultnotE_CODE': instance.readingorderresultnoteCode,
      'digitsnumber': instance.digitsnumber,
      'coefficient': ReadingOrder._formatDecimal(instance.coefficient),
      'zwnummer': instance.zwnummer,
      'zpruefkl': instance.zpruefkl,
      'zzwtyp': instance.zzwtyp,
      'zkennziff': instance.zkennziff,
      'zwerT1': instance.zwert1,
      'itinerarY_CODENavigation': instance.itinerarycodenavigation,
      'workorderbatcH_CODENavigation': instance.workorderbatchcodenavigation,
    };
